language: php

php: 
  - 5.3
  - 5.4

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --prefer-source --no-interaction --dev

script:
  - mkdir -p build/logs
  - phpunit

after_script:
  - php vendor/bin/coveralls --config test/.coveralls.yml -v